### ISSUE TITLE
PHP Fatal calling removeSheet

### ISSUE THREAD

**Issue by fansanelli** [easyise/eiseXLSX#15]
Hello,

I'm trying to remove a sheet from my Xlsx file using this code:
```

require __DIR__ . '/vendor/autoload.php';

$xlsx = new eiseXLSX("test2.xlsx");
$xlsx->removeSheet($xlsx->findSheetByName("Foglio3"));

$xlsx->Output("output/mynewfile.xlsx", "F");

```
I got a FATAL error:
```
[Fri Oct 11 16:49:39.619899 2019] [php7:notice] [pid 10475] [client 127.0.0.1:34758] PHP Notice:  Undefined index: /xl/worksheets/_rels/sheet1.xml.rels in /home/francesco/eclipse-workspace/commercialisti/vendor/easyise/eisexlsx/eiseXLSX.php on line 813
[Fri Oct 11 16:49:39.619948 2019] [php7:notice] [pid 10475] [client 127.0.0.1:34758] PHP Notice:  Trying to get property 'Relationship' of non-object in /home/francesco/eclipse-workspace/commercialisti/vendor/easyise/eisexlsx/eiseXLSX.php on line 813
[Fri Oct 11 16:49:39.620198 2019] [php7:notice] [pid 10475] [client 127.0.0.1:34758] PHP Notice:  Undefined index: /xl/worksheets/_rels/sheet3.xml.rels in /home/francesco/eclipse-workspace/commercialisti/vendor/easyise/eisexlsx/eiseXLSX.php on line 1441
[Fri Oct 11 16:49:39.620219 2019] [php7:notice] [pid 10475] [client 127.0.0.1:34758] PHP Notice:  Trying to get property 'Relationship' of non-object in /home/francesco/eclipse-workspace/commercialisti/vendor/easyise/eisexlsx/eiseXLSX.php on line 1441
[Fri Oct 11 16:49:39.620229 2019] [php7:notice] [pid 10475] [client 127.0.0.1:34758] PHP Notice:  Undefined index: /xl/worksheets/_rels/sheet3.xml.rels in /home/francesco/eclipse-workspace/commercialisti/vendor/easyise/eisexlsx/eiseXLSX.php on line 1509
[Fri Oct 11 16:49:39.620283 2019] [php7:warn] [pid 10475] [client 127.0.0.1:34758] PHP Warning:  eiseXLSX::updateAppXML(): Node no longer exists in /home/francesco/eclipse-workspace/commercialisti/vendor/easyise/eisexlsx/eiseXLSX.php on line 1478
[Fri Oct 11 16:49:39.620294 2019] [php7:notice] [pid 10475] [client 127.0.0.1:34758] PHP Notice:  Trying to get property 'variant' of non-object in /home/francesco/eclipse-workspace/commercialisti/vendor/easyise/eisexlsx/eiseXLSX.php on line 1478
[Fri Oct 11 16:49:39.620302 2019] [php7:notice] [pid 10475] [client 127.0.0.1:34758] PHP Notice:  Trying to get property 'i4' of non-object in /home/francesco/eclipse-workspace/commercialisti/vendor/easyise/eisexlsx/eiseXLSX.php on line 1478
[Fri Oct 11 16:49:39.620314 2019] [php7:warn] [pid 10475] [client 127.0.0.1:34758] PHP Warning:  eiseXLSX::updateAppXML(): Node no longer exists in /home/francesco/eclipse-workspace/commercialisti/vendor/easyise/eisexlsx/eiseXLSX.php on line 1479
[Fri Oct 11 16:49:39.620323 2019] [php7:warn] [pid 10475] [client 127.0.0.1:34758] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /home/francesco/eclipse-workspace/commercialisti/vendor/easyise/eisexlsx/eiseXLSX.php on line 1479
[Fri Oct 11 16:49:39.620334 2019] [php7:warn] [pid 10475] [client 127.0.0.1:34758] PHP Warning:  eiseXLSX::updateAppXML(): Node no longer exists in /home/francesco/eclipse-workspace/commercialisti/vendor/easyise/eisexlsx/eiseXLSX.php on line 1482
[Fri Oct 11 16:49:39.620344 2019] [php7:warn] [pid 10475] [client 127.0.0.1:34758] PHP Warning:  eiseXLSX::updateAppXML(): Node no longer exists in /home/francesco/eclipse-workspace/commercialisti/vendor/easyise/eisexlsx/eiseXLSX.php on line 1482
[Fri Oct 11 16:49:39.620352 2019] [php7:warn] [pid 10475] [client 127.0.0.1:34758] PHP Warning:  eiseXLSX::updateAppXML(): Node no longer exists in /home/francesco/eclipse-workspace/commercialisti/vendor/easyise/eisexlsx/eiseXLSX.php on line 1482
[Fri Oct 11 16:49:39.620362 2019] [php7:warn] [pid 10475] [client 127.0.0.1:34758] PHP Warning:  eiseXLSX::updateAppXML(): Node no longer exists in /home/francesco/eclipse-workspace/commercialisti/vendor/easyise/eisexlsx/eiseXLSX.php on line 1482
[Fri Oct 11 16:49:39.620398 2019] [php7:warn] [pid 10475] [client 127.0.0.1:34758] PHP Warning:  eiseXLSX::updateAppXML(): Node no longer exists in /home/francesco/eclipse-workspace/commercialisti/vendor/easyise/eisexlsx/eiseXLSX.php on line 1482
[Fri Oct 11 16:49:39.620407 2019] [php7:warn] [pid 10475] [client 127.0.0.1:34758] PHP Warning:  eiseXLSX::updateAppXML(): Node no longer exists in /home/francesco/eclipse-workspace/commercialisti/vendor/easyise/eisexlsx/eiseXLSX.php on line 1482
[Fri Oct 11 16:49:39.620416 2019] [php7:warn] [pid 10475] [client 127.0.0.1:34758] PHP Warning:  eiseXLSX::updateAppXML(): Node no longer exists in /home/francesco/eclipse-workspace/commercialisti/vendor/easyise/eisexlsx/eiseXLSX.php on line 1482
[Fri Oct 11 16:49:39.620424 2019] [php7:notice] [pid 10475] [client 127.0.0.1:34758] PHP Notice:  Indirect modification of overloaded element of SimpleXMLElement has no effect in /home/francesco/eclipse-workspace/commercialisti/vendor/easyise/eisexlsx/eiseXLSX.php on line 1482
[Fri Oct 11 16:49:39.620437 2019] [php7:warn] [pid 10475] [client 127.0.0.1:34758] PHP Warning:  eiseXLSX::updateAppXML(): Node no longer exists in /home/francesco/eclipse-workspace/commercialisti/vendor/easyise/eisexlsx/eiseXLSX.php on line 1490
[Fri Oct 11 16:49:39.620449 2019] [php7:warn] [pid 10475] [client 127.0.0.1:34758] PHP Warning:  dom_import_simplexml() expects parameter 1 to be object, null given in /home/francesco/eclipse-workspace/commercialisti/vendor/easyise/eisexlsx/eiseXLSX.php on line 1491
[Fri Oct 11 16:49:39.620496 2019] [php7:error] [pid 10475] [client 127.0.0.1:34758] PHP Fatal error:  Uncaught Error: Call to a member function addChild() on null in /home/francesco/eclipse-workspace/commercialisti/vendor/easyise/eisexlsx/eiseXLSX.php:1494\nStack trace:\n#0 /home/francesco/eclipse-workspace/commercialisti/vendor/easyise/eisexlsx/eiseXLSX.php(1470): eiseXLSX->updateAppXML()\n#1 /home/francesco/eclipse-workspace/commercialisti/vendor/easyise/eisexlsx/eiseXLSX.php(857): eiseXLSX->updateWorkbookLinks()\n#2 /home/francesco/eclipse-workspace/commercialisti/test_scrittura2.php(10): eiseXLSX->removeSheet('1')\n#3 {main}\n  thrown in /home/francesco/eclipse-workspace/commercialisti/vendor/easyise/eisexlsx/eiseXLSX.php on line 1494

```
My environment:
```
$ php -version
PHP 7.2.19-0ubuntu0.18.04.2 (cli) (built: Aug 12 2019 19:34:28) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.19-0ubuntu0.18.04.2, Copyright (c) 1999-2018, by Zend Technologies
```

Can you please check?
Many thanks
Best Regards,
Francesco

**Comment by easyise** [comment]
Hi! Can you please send me your Excel file? ie@e-ise.com. Thanks!

**Comment by fansanelli** [comment]
hi @easyise 
please find the file in attachment

[test2.xlsx](https://github.com/easyise/eiseXLSX/files/3777688/test2.xlsx)
